/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefenseproject;

import java.awt.BorderLayout;

/**
 *
 * @author Michael
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static int pane = 0;
    private static GamePanel gamePanel;

    private static MainFrame instance = null;
   
    /**
     * get singleton instance of the mainframe
     * @return 
     */
    public static MainFrame getInstance() {
       if(instance == null) {
          instance = new MainFrame();
       }
       return instance;
    }
    /**
     * Creates new form MainFrame
     */
    protected MainFrame() {
        initComponents();
        addKeyListener( new KeyHandler() );
        
        gamePanel = new GamePanel();
        
    }
    
    private void updatePanes(){
        if ( pane == 0 ) {
            remove( gamePanel );
            //TODO build main menu
        }
        else if ( pane == 1 ){
            setLayout(new BorderLayout());
            add( gamePanel, BorderLayout.CENTER);
        }
        pack();
        revalidate();
    }
    
    public static boolean runAction( String action ){
        if ( action.equals( "paneChange" ) ){
            if ( pane == 0 ){
				pane = 1;
			} else {
				pane = 0;
			}
            MainFrame.getInstance().updatePanes();
            return true;
        }
        else if( action.equals( "debug" ) ){
            gamePanel.getBankPane1().setMoneyLabel( "1234.34" );
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tower Defence");
        setMinimumSize(new java.awt.Dimension(1007, 549));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
