/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefenseproject;

import javax.swing.JLabel;

/**
 *
 * @author Michael
 */
public class TowerInfoPane extends javax.swing.JPanel {

    /**
     * Creates new form TowerInfoPane
     */
    public TowerInfoPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        damageLabel = new javax.swing.JLabel();
        reloadLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        upgradeLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Title of tower here");

        jLabel2.setText("Type");

        jLabel3.setText("Damage");

        jLabel4.setText("Reload");

        typeLabel.setText("Ground");

        damageLabel.setText("12345");

        reloadLabel.setText("2s");

        jLabel8.setText("Level");

        jLabel9.setText("Upgrade");

        jLabel10.setText("idk");

        levelLabel.setText("1");

        upgradeLabel.setText("2500");

        jLabel13.setText("idk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(damageLabel)
                            .addComponent(reloadLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(upgradeLabel)
                            .addComponent(levelLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeLabel)
                    .addComponent(jLabel8)
                    .addComponent(levelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(damageLabel)
                    .addComponent(jLabel9)
                    .addComponent(upgradeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reloadLabel)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getDamageLabel() {
        return damageLabel.getText();
    }

    public void setDamageLabel(String damageLabel) {
        this.damageLabel.setText( damageLabel );
    }

    public String getLevelLabel() {
        return levelLabel.getText();
    }

    public void setLevelLabel(String levelLabel) {
        this.levelLabel.setText( levelLabel );
    }

    public String getReloadLabel() {
        return reloadLabel.getText();
    }

    public void setReloadLabel(String reloadLabel) {
        this.reloadLabel.setText( reloadLabel );
    }

    public String getTypeLabel() {
        return typeLabel.getText();
    }

    public void setTypeLabel(String typeLabel) {
        this.typeLabel.setText( typeLabel );
    }

    public String getUpgradeLabel() {
        return upgradeLabel.getText();
    }

    public void setUpgradeLabel(String upgradeLabel) {
        this.upgradeLabel.setText( upgradeLabel );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel damageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel reloadLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel upgradeLabel;
    // End of variables declaration//GEN-END:variables
}
