/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefenseproject;

import javax.swing.JLabel;

/**
 *
 * @author Michael
 */
public class WavePane extends javax.swing.JPanel {

    /**
     * Creates new form WavePane
     */
    public WavePane() {
        initComponents();
    }

    public String getNextWaveLabel() {
        return nextWaveLabel.getText();
    }

    public void setNextWaveLabel(String nextWaveLabel) {
        this.nextWaveLabel.setText( nextWaveLabel );
    }

    public String getWaveLabel() {
        return waveLabel.getText();
    }

    public void setWaveLabel(String waveLabel) {
        this.waveLabel.setText( waveLabel );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        waveSendLabel = new javax.swing.JLabel();
        pauseLabel = new javax.swing.JLabel();
        nextWaveLabel = new javax.swing.JLabel();
        waveLabel = new javax.swing.JLabel();

        jLabel1.setText("Wave");

        jLabel2.setText("Next Wave");

        waveSendLabel.setText("Send Now");

        pauseLabel.setText("Pause");

        nextWaveLabel.setText("60secs");

        waveLabel.setText("16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waveSendLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextWaveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pauseLabel)
                    .addComponent(waveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(waveLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nextWaveLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waveSendLabel)
                    .addComponent(pauseLabel))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nextWaveLabel;
    private javax.swing.JLabel pauseLabel;
    private javax.swing.JLabel waveLabel;
    private javax.swing.JLabel waveSendLabel;
    // End of variables declaration//GEN-END:variables
}
